# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190313_1314'),
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=30)),
                ('slot', models.DateField(default=None, null=True)),
                ('stu1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.problems')),
            ],
        ),
    ]
