# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='problem',
            new_name='problem_type',
        ),
    ]
