# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_auto_20190313_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='stu1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.problems'),
        ),
    ]
