# Generated by Django 2.1.7 on 2019-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0005_notifications_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='problems_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
