# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0010_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='no_items',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
