# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0011_stock_no_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
