# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('branch', models.CharField(max_length=30)),
                ('class_room', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot', models.DateTimeField(default=None)),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='problems',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
