# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_type',
        ),
    ]
