# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_problems_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
