# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190312_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='slot',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
