# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_postrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='galley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='rguktlogo.jpg', upload_to='gallery/')),
            ],
        ),
    ]
