# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_galley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galley',
            name='img',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
