# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_galley'),
    ]

    operations = [
        migrations.DeleteModel(
            name='galley',
        ),
    ]
