# Generated by Django 2.1.7 on 2019-06-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequest',
            name='idnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.register'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
