# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20190801_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='tech_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
